# render.yaml
services:
  - type: web
    name: prepair-central-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
